### ISSUE TITLE
Write command for switch does not work.

### ISSUE THREAD

**Issue by geeknam** [monster1025/aqara-mqtt#1]
Hey there,

I'm writing my own python bindings and found this repo.

I'm trying to emulate a switch click event with:
```python
{"model": "switch", "cmd": "write", "data": {"status": "click", "key": "A1997D2D474F616BB03FCEC6D2XXX"}, "short_id": 46909, "sid": "158d00011XXXXX"}
```

But I get back:
```python
{'cmd': 'write_ack', 'data': {"error":"Unsupported device"}, 'sid': '158d00011XXXXX'}
```
It looks like you can only write to a `plug` and a `ctrl`?
Have you been able to successfully write a click to a switch?
Everything else works: read, get_id_list. Maybe you can enlighten me?

**Comment by monster1025** [comment]
Sorry - but switch is xiaomi button (for example: http://www.gearbest.com/smart-light-bulb/pp_257679.html ) - you can't 'control' it, because there is nothing to control (it can't do anything).

If you want to "emulate" click for your software - you must do it inside your binding without sending commands to aqara (xiaomi) gateway.

For example: I can "emulate" clicks for my software (home assistant) if I will send command "home/switch/kitchen/status" -> " click" to mqtt, this will equal to event generated by button click (and really no matter who generate this message to mqtt).

So, gateway can't help you with emulation, but it will accept writes for gateway's rgb property or plug's status property.

**Comment by geeknam** [comment]
Yes, I wanted to generate the `button click` event and let Gateway rules decide themselves. It's ok I think I will find a different approach. Sounds like I have to use an external hub with a message bus. Thanks for answering :)
